name: Challenge Test

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  awesome:
    name: Awesome Action
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: rrafols/challenge_action
          ref: v1.1
          token: ${{ secrets.GIT_HUB_TOKEN }} # stored in GitHub secrets
          path: .github/rrafols/challenge_action
      - name: Run My Action
        uses: ./.rrafols/challenge_action
